## ENTORNO DE TRABAJO DE PRODUCCION ##
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 1
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always

email:
  host: smtp.gmail.com
  port: 587
  username: nocountryc1529@gmail.com
  password: yogbzwcgpgvgxrce
  porties:
    mail:
      smtp:
        starttls:
          enable: true
